### ISSUE TITLE
Native image problem

### ISSUE THREAD

**Issue by niclarcipretti** [bufferings/micronaut-petclinic#7]
Hi @bufferings,

I was compiling your app as a native graalvm image, but, at the end of the compilation, I got the following warning:

`Warning: Image 'com.example.micronaut.petclinic.petclinicapplication' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation).`

Afaik, this is exactly what a native image shouldn't be. 

So, after some research, I discovered that you have to run native-image wiht a --no-fallback flag to realy have a JDK independent executable.

I have a similar project here (but just the backend) and couldn't manage to make native image injects EntityManager. If you happen to achieve this with the --no-fallback flag, can you answer this issue and let me know how?

Thanks in advance man!

Nikao

**Comment by bufferings** [comment]
Thank you for the comment. You're right. The latest commit doesn't work well. Sorry. If it's ok for you to use GraalVM 1.0.0-RC16, you can use this tag and you can successfully create a native image.
https://github.com/bufferings/micronaut-petclinic/tree/rc16

Regarding GraalVM 19.0.0, I committed a change now.
https://github.com/bufferings/micronaut-petclinic/pull/8/files

This will make the native-image process continue, but there's a problem with the GraalVM 19.
To make the build succeed we need following fix.
https://github.com/oracle/graal/commit/c6237d219a91c82b1954dfbfa0898ed917db09eb

I'm currently waiting the next GraalVM release, or I would like to find a way to build native-image jar file so that we can use it temporarily.

**Comment by bufferings** [comment]
For now, I created a Docker image to use master branch of GraalVM.
https://github.com/bufferings/micronaut-petclinic/pull/9

So I close this issue.
